### PR TITLE
added shiny "object"

### PR DESCRIPTION
**Pull request by dbutlerdb**

### CODE REVIEW

**Comment by hjwp** [comment]
thanks, the turn of phrase "the new shiny" was intentional, that noun form of shiny is a bit weird i know but it's a thing i'm used to saying and hearing.  some examples here. https://www.urbandictionary.com/define.php?term=shiny&page=2

please do send any other typo fixes and suggestions!  i'd rather have too many than too few.

**Comment by hjwp** [comment]
thanks, the turn of phrase "the new shiny" was intentional, that noun form of shiny is a bit weird i know but it's a thing i'm used to saying and hearing.  some examples here. https://www.urbandictionary.com/define.php?term=shiny&page=2

please do send any other typo fixes and suggestions!  i'd rather have too many than too few.

**Comment by hjwp** [comment]
thanks, the turn of phrase "the new shiny" was intentional, that noun form of shiny is a bit weird i know but it's a thing i'm used to saying and hearing.  some examples here. https://www.urbandictionary.com/define.php?term=shiny&page=2

please do send any other typo fixes and suggestions!  i'd rather have too many than too few.

**Comment by jwm-evans** [comment]
As a colloquialism, "object" is not strictly required in "the new shiny". The line reads just fine in its current form (IMHO).

**Pull request closed without merging**
